apiVersion: v1
kind: Service
metadata:
  name: external-database-service
spec:
  type: ExternalName
<<<<<<< Updated upstream
  externalName: nencyravaliya.me
=======
  externalName: api.ananya.com
>>>>>>> Stashed changes
